project_name: gh-lazy

builds:
  - id: macos
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X github.com/igorcosta/gh-lazy/pkg/version.Version={{.Version}}
      - -X github.com/igorcosta/gh-lazy/pkg/version.Commit={{.Commit}}
      - -X github.com/igorcosta/gh-lazy/pkg/version.Date={{.Date}}
  - id: other
    main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X github.com/igorcosta/gh-lazy/pkg/version.Version={{.Version}}
      - -X github.com/igorcosta/gh-lazy/pkg/version.Commit={{.Commit}}
      - -X github.com/igorcosta/gh-lazy/pkg/version.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: igorcosta
    name: gh-lazy

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch