project_name: lazy

builds:
  - id: macos
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    env:
      - CGO_ENABLED=1
  - id: other
    main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: igorcosta
    name: gh-lazy

changelog:
  sort: asc
