name: 🚀 Feature Request
description: Suggest an idea for this project (because we're too lazy to think of everything ourselves)
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - igorcosta
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Let's make Lazy even lazier!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when I have to [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. The lazier, the better!
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered. Or just tell us you're too lazy to think of alternatives.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here. Memes are welcome!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/igorcosta/gh-lazy/blob/main/CODE_OF_CONDUCT.md) (and to uphold the principles of laziness)
      options:
        - label: I agree to follow this project's Code of Conduct (and to never manually create GitHub projects again)
          required: true